In [3]:
import sklearn.svm
import sklearn.metrics
import numpy as np
import pandas
import random
from homework4_jpcaltabiano_mmthant import SVM4342

# Load data
d = pandas.read_csv('train.csv')
print(d[:2])
d = d.sample(frac=1) # randomly shuffle rows
print(d[:2])

y = np.array(d.target)  # Labels
X = np.array(d.iloc[:,2:])  # Features

# this should be randomly selected
train_y = y[:100000]
train_X = X[:100000]

test_y = y[100000:]
test_X = X[100000:]

# Load test set (not needed?)
# td = pandas.read_csv('test.csv')
# ty = np.array(pandas.read_csv('sample_submission.csv').target)
# tX = np.array(td.iloc[:,1:])

   ID_code  target    var_0   var_1    var_2  var_3    var_4   var_5   var_6  \
0  train_0       0   8.9255 -6.7863  11.9081  5.093  11.4607 -9.2834  5.1187   
1  train_1       0  11.5006 -4.1473  13.8588  5.389  12.3622  7.0433  5.6208   

     var_7  ...  var_190  var_191  var_192  var_193  var_194  var_195  \
0  18.6266  ...   4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  16.5338  ...   7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1   8.1267   8.7889  18.3560   1.9518  

[2 rows x 202 columns]
             ID_code  target    var_0   var_1    var_2   var_3    var_4  \
101333  train_101333       0  14.4280 -1.9823  12.6307  6.0561  10.6738   
157667  train_157667       0   9.8566  5.5852  11.1883  9.1968  10.6613   

          var_5   var_6    var_7  ...  var_190  var_191  var_192  var_193  \
101333  -9.4778  4.3949  18.1882  ...   7.4107  10.0726  -0.1945   5.0773   
157667 -10.2296

In [4]:
train_subX = np.vsplit(train_X, 1000)
train_suby = np.split(train_y, 1000)

svms = []
for i in range(len(train_subX)):
    svm = sklearn.svm.SVC(kernel='linear', C=1e15)  # 1e15 -- approximate hard-margin
    svm.fit(train_subX[i], train_suby[i])
    svms.append(svm)

In [5]:
# heads up - doing the loop for all in svms takes a very long time, loop thru svms[:5] to test

preds = np.zeros((100000,))
for i in svms[:5]:
    preds += i.decision_function(test_X)
    
print(preds[:5])

preds = preds / 5

print(preds[:5])
print(test_y[:5])


preds = np.where(preds > 0.5, 1, 0)

acc = np.mean(preds == test_y)
print(acc)

[-4.71804805 -5.14163139 -7.67875802 -5.23924925 -7.00382432]
[-0.94360961 -1.02832628 -1.5357516  -1.04784985 -1.40076486]
[0 0 0 0 0]
0.89937
